version: '3.3'

services:
  streamlit:
    image: cattracker2.azurecr.io/streamlit-rpi:latest
#    build: ./
    command: streamlit run streamlit_app.py --server.port 8080 --server.headless=true --browser.gatherUsageStats=false
    volumes:
      - ./app/:/app/
    ports:
      - 8080:8080
      - 4430:4430
